appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: p3GHwmOVOy4S3xAeYGwgHkMiyhBmzTXrumLq8EgTj1fcuRT1kRcN6CFZgjgldIcV+T4FFEmXpJvSqm4u8i+k9dLXa+qsgeF7WiEP04Nk4YfqezfLRQhQBdWXEs3KWTigj4fV6ASoBqfzDziwXYjFH6kueq0PpmQLqiBDgvS8lSGyC4uu6eWclpDcgLQmQTNaCqMl0aAAKJRg+0UqZ+YRXimbXzpdTdtzaKugr0eVBRyCOuh251lsv6I6Ihb0LnmiqBy+YmVY+FdhUTNR1cjhJxwbAAE9SdDG695m5n9enry/j1OkqGzEJ3+lB8Q1rxoizpeyHA8cd9bkVDNC+KY/cL6nfaKR2RtFB2Moc6SU8/AM/h0DtuXHDcQ2+/95bgMYD1UuwzB1Zls+yjbIe4+nB8TAJHd9F3dbGikz5IzoC8nou9L2lZzds+O3imuhUlYd5OZVAFSX/FsvnhdEeEx1C+JKmHI6C1JaJd0KcCw5pQQaSVYgtB//CdUaM8SlvAy4GaYK8XGMvJ8Px3MIArag8ASn5vIm84MhLtECLFYbPOYKMMtSMMGS/RiBe5na5bzqbAiMt9qTlla+YAmfz0jSFqMbSUGP7pm76aRsj2BzLf3mUvyX1vWF5Feh1PCO5X1zszanwH3aIfVgc2GSo7NdEiX+oBjPY0zjPOi1WA5k0qs=
conda_forge_output_validation: false
